name: Deployment Orchestrator

on:
  workflow_run:
    workflows: ['Pipeline']
    branches: [main]
    types: [completed]
  workflow_dispatch:

jobs:
  deploy-firebase:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/deploy-firebase.yml
    with:
      ref: ${{ github.ref }}
    secrets: inherit
